[meta]
support_server_invite = "https://discord.gg/G5pEdUp"
invite_url_permissions = "805694544"
admins = [""]

[storage]
postgres_url = "postgres://postgres:postgres@localhost:5432/suggester?schema=public"
redis_url = "redis://localhost"

[web_server]
host = "127.0.0.1"
port = 3000

[[dev]]
token = ""
public_key = ""
application_id = ""
guild_id = ""
channel_id = ""
user_id = ""
