#!/usr/bin/env bash

root="$(dirname "$0")/.."

protoc \
  --plugin="$root/node_modules/.bin/protoc-gen-ts_proto" \
  --ts_proto_out="$root/lib/protos" \
  --ts_proto_opt="esModuleInterop=true" \
  -I="$root/protos" \
  $root/protos/*.proto
